### ISSUE TITLE
Xpresso data and website give 403 error

### ISSUE THREAD

**Issue by pbandjanet** [vagarwal87/Xpresso#2]
The Xpresso website (https://xpresso.gs.washington.edu/) gives a 403 error. In addition, the ipython notebook also will not download the datasets in the first cell because of a 403 error. Is this a mistake?

**Comment by vagarwal87** [comment]
Hi,

Yes someone brought this to my awareness as well. This appears to be a new message lately because the entire website is down due to server maintenance. I already raised the issue to my school's IT staff and I think it should be fixed within a few days ideally. Will update here once it has been fixed. Thanks for your patience!

**Comment by pbandjanet** [comment]
Sounds good. Thanks for the quick response!

**Comment by vagarwal87** [comment]
Okay looks like this should be resolved now, with all back up online. Feel free to reopen ticket if you still have any issues. Thanks!
